spring.application.name=patient-service

# H2 Console Configuration
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Datasource Configuration
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

#we can remove this property it is selected automatically
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Automatically updates the database schema based on JPA entities without dropping existing data.
# Useful in development for quick schema evolution, but not recommended for production.
#spring.jpa.hibernate.ddl-auto=update

# Ensures that SQL initialization scripts (schema.sql, data.sql) are always executed at startup.
# Commonly used for setting up initial database structure or seed data during development/testing.
#spring.sql.init.mode=always

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

server.port=4000

# Ensures that Hibernate fully initializes the database schema before Spring executes
# schema.sql or data.sql scripts. This guarantees that tables created via @Entity
# are available before any data initialization scripts run.
#spring.jpa.defer-datasource-initialization=true

#log levels
logging.level.root=info